#ifndef MACROS_H
#define MACROS_H

#define msvc_expand_va_args(X) X

#define Args_(...) __VA_ARGS__
#define STRIP_PARENTHESES_(X) X
#define mc_strip_parentheses(X) STRIP_PARENTHESES_(Args_ X)
//EXPAND((A, B)) -> STRIP_PARENS(Args_(a,b)) -> 

// Make a FOREACH macro
#define fe_1(WHAT, X)		WHAT(X)
#define fe_2(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_1( WHAT, __VA_ARGS__) )
#define fe_3(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_2( WHAT, __VA_ARGS__) )
#define fe_4(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_3( WHAT, __VA_ARGS__) )
#define fe_5(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_4( WHAT, __VA_ARGS__) )
#define fe_6(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_5( WHAT, __VA_ARGS__) )
#define fe_7(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_6( WHAT, __VA_ARGS__) )
#define fe_8(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_7( WHAT, __VA_ARGS__) )
#define fe_9(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_8( WHAT, __VA_ARGS__) )
#define fe_10(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_9( WHAT, __VA_ARGS__) )
#define fe_11(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_10( WHAT, __VA_ARGS__) )
#define fe_12(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_11( WHAT, __VA_ARGS__) )
#define fe_13(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_12( WHAT, __VA_ARGS__) )
#define fe_14(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_13( WHAT, __VA_ARGS__) )
#define fe_15(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_14( WHAT, __VA_ARGS__) )
#define fe_16(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_15( WHAT, __VA_ARGS__) )
#define fe_17(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_16( WHAT, __VA_ARGS__) )
#define fe_18(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_17( WHAT, __VA_ARGS__) )
#define fe_19(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_18( WHAT, __VA_ARGS__) )
#define fe_20(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_19( WHAT, __VA_ARGS__) )
#define fe_21(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_20( WHAT, __VA_ARGS__) )
#define fe_22(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_21( WHAT, __VA_ARGS__) )
#define fe_23(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_22( WHAT, __VA_ARGS__) )
#define fe_24(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_23( WHAT, __VA_ARGS__) )
#define fe_25(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_24( WHAT, __VA_ARGS__) )
#define fe_26(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_25( WHAT, __VA_ARGS__) )
#define fe_27(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_26( WHAT, __VA_ARGS__) )
#define fe_28(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_27( WHAT, __VA_ARGS__) )
#define fe_29(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_28( WHAT, __VA_ARGS__) )
#define fe_30(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_29( WHAT, __VA_ARGS__) )
#define fe_31(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_30( WHAT, __VA_ARGS__) )
#define fe_32(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_31( WHAT, __VA_ARGS__) )
#define fe_33(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_32( WHAT, __VA_ARGS__) )
#define fe_34(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_33( WHAT, __VA_ARGS__) )
#define fe_35(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_34( WHAT, __VA_ARGS__) )
#define fe_36(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_35( WHAT, __VA_ARGS__) )
#define fe_37(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_36( WHAT, __VA_ARGS__) )
#define fe_38(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_37( WHAT, __VA_ARGS__) )
#define fe_39(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_38( WHAT, __VA_ARGS__) )
#define fe_40(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_39( WHAT, __VA_ARGS__) )
#define fe_41(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_40( WHAT, __VA_ARGS__) )
#define fe_42(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_41( WHAT, __VA_ARGS__) )
#define fe_43(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_42( WHAT, __VA_ARGS__) )
#define fe_44(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_43( WHAT, __VA_ARGS__) )
#define fe_45(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_44( WHAT, __VA_ARGS__) )
#define fe_46(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_45( WHAT, __VA_ARGS__) )
#define fe_47(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_46( WHAT, __VA_ARGS__) )
#define fe_48(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_47( WHAT, __VA_ARGS__) )
#define fe_49(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_48( WHAT, __VA_ARGS__) )
#define fe_50(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_49( WHAT, __VA_ARGS__) )
#define fe_51(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_50( WHAT, __VA_ARGS__) )
#define fe_52(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_51( WHAT, __VA_ARGS__) )
#define fe_53(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_52( WHAT, __VA_ARGS__) )
#define fe_54(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_53( WHAT, __VA_ARGS__) )
#define fe_55(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_54( WHAT, __VA_ARGS__) )
#define fe_56(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_55( WHAT, __VA_ARGS__) )
#define fe_57(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_56( WHAT, __VA_ARGS__) )
#define fe_58(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_57( WHAT, __VA_ARGS__) )
#define fe_59(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_58( WHAT, __VA_ARGS__) )
#define fe_60(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_59( WHAT, __VA_ARGS__) )
#define fe_61(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_60( WHAT, __VA_ARGS__) )
#define fe_62(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_61( WHAT, __VA_ARGS__) )
#define fe_63(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_62( WHAT, __VA_ARGS__) )
#define fe_64(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_63( WHAT, __VA_ARGS__) )
#define fe_65(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_64( WHAT, __VA_ARGS__) )
#define fe_66(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_65( WHAT, __VA_ARGS__) )
#define fe_67(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_66( WHAT, __VA_ARGS__) )
#define fe_68(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_67( WHAT, __VA_ARGS__) )
#define fe_69(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_68( WHAT, __VA_ARGS__) )
#define fe_70(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_69( WHAT, __VA_ARGS__) )
#define fe_71(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_70( WHAT, __VA_ARGS__) )
#define fe_72(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_71( WHAT, __VA_ARGS__) )
#define fe_73(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_72( WHAT, __VA_ARGS__) )
#define fe_74(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_73( WHAT, __VA_ARGS__) )
#define fe_75(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_74( WHAT, __VA_ARGS__) )
#define fe_76(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_75( WHAT, __VA_ARGS__) )
#define fe_77(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_76( WHAT, __VA_ARGS__) )
#define fe_78(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_77( WHAT, __VA_ARGS__) )
#define fe_79(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_78( WHAT, __VA_ARGS__) )
#define fe_80(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_79( WHAT, __VA_ARGS__) )
#define fe_81(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_80( WHAT, __VA_ARGS__) )
#define fe_82(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_81( WHAT, __VA_ARGS__) )
#define fe_83(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_82( WHAT, __VA_ARGS__) )
#define fe_84(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_83( WHAT, __VA_ARGS__) )
#define fe_85(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_84( WHAT, __VA_ARGS__) )
#define fe_86(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_85( WHAT, __VA_ARGS__) )
#define fe_87(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_86( WHAT, __VA_ARGS__) )
#define fe_88(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_87( WHAT, __VA_ARGS__) )
#define fe_89(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_88( WHAT, __VA_ARGS__) )
#define fe_90(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_89( WHAT, __VA_ARGS__) )
#define fe_91(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_90( WHAT, __VA_ARGS__) )
#define fe_92(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_91( WHAT, __VA_ARGS__) )
#define fe_93(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_92( WHAT, __VA_ARGS__) )
#define fe_94(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_93( WHAT, __VA_ARGS__) )
#define fe_95(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_94( WHAT, __VA_ARGS__) )
#define fe_96(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_95( WHAT, __VA_ARGS__) )
#define fe_97(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_96( WHAT, __VA_ARGS__) )
#define fe_98(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_97( WHAT, __VA_ARGS__) )
#define fe_99(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_98( WHAT, __VA_ARGS__) )
#define fe_100(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_99( WHAT, __VA_ARGS__) )
#define fe_101(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_100( WHAT, __VA_ARGS__) )
#define fe_102(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_101( WHAT, __VA_ARGS__) )
#define fe_103(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_102( WHAT, __VA_ARGS__) )
#define fe_104(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_103( WHAT, __VA_ARGS__) )
#define fe_105(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_104( WHAT, __VA_ARGS__) )
#define fe_106(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_105( WHAT, __VA_ARGS__) )
#define fe_107(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_106( WHAT, __VA_ARGS__) )
#define fe_108(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_107( WHAT, __VA_ARGS__) )
#define fe_109(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_108( WHAT, __VA_ARGS__) )
#define fe_110(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_109( WHAT, __VA_ARGS__) )
#define fe_111(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_110( WHAT, __VA_ARGS__) )
#define fe_112(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_111( WHAT, __VA_ARGS__) )
#define fe_113(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_112( WHAT, __VA_ARGS__) )
#define fe_114(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_113( WHAT, __VA_ARGS__) )
#define fe_115(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_114( WHAT, __VA_ARGS__) )
#define fe_116(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_115( WHAT, __VA_ARGS__) )
#define fe_117(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_116( WHAT, __VA_ARGS__) )
#define fe_118(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_117( WHAT, __VA_ARGS__) )
#define fe_119(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_118( WHAT, __VA_ARGS__) )
#define fe_120(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_119( WHAT, __VA_ARGS__) )
#define fe_121(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_120( WHAT, __VA_ARGS__) )
#define fe_122(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_121( WHAT, __VA_ARGS__) )
#define fe_123(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_122( WHAT, __VA_ARGS__) )
#define fe_124(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_123( WHAT, __VA_ARGS__) )
#define fe_125(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_124( WHAT, __VA_ARGS__) )
#define fe_126(WHAT, X, ...)WHAT(X)msvc_expand_va_args( fe_125( WHAT, __VA_ARGS__) )

// Make a FOREACH macro
#define fe_i_1(WHAT, X) WHAT(X, 1)
#define fe_i_2(WHAT, X, ...)WHAT(X, 2)msvc_expand_va_args( fe_i_1( WHAT, __VA_ARGS__) )
#define fe_i_3(WHAT, X, ...)WHAT(X, 3)msvc_expand_va_args( fe_i_2( WHAT, __VA_ARGS__) )
#define fe_i_4(WHAT, X, ...)WHAT(X, 4)msvc_expand_va_args( fe_i_3( WHAT, __VA_ARGS__) )
#define fe_i_5(WHAT, X, ...)WHAT(X, 5)msvc_expand_va_args( fe_i_4( WHAT, __VA_ARGS__) )
#define fe_i_6(WHAT, X, ...)WHAT(X, 6)msvc_expand_va_args( fe_i_5( WHAT, __VA_ARGS__) )
#define fe_i_7(WHAT, X, ...)WHAT(X, 7)msvc_expand_va_args( fe_i_6( WHAT, __VA_ARGS__) )
#define fe_i_8(WHAT, X, ...)WHAT(X, 8)msvc_expand_va_args( fe_i_7( WHAT, __VA_ARGS__) )
#define fe_i_9(WHAT, X, ...)WHAT(X, 9)msvc_expand_va_args( fe_i_8( WHAT, __VA_ARGS__) )
#define fe_i_10(WHAT, X, ...)WHAT(X, 10)msvc_expand_va_args( fe_i_9( WHAT, __VA_ARGS__) )
#define fe_i_11(WHAT, X, ...)WHAT(X, 11)msvc_expand_va_args( fe_i_10( WHAT, __VA_ARGS__) )
#define fe_i_12(WHAT, X, ...)WHAT(X, 12)msvc_expand_va_args( fe_i_11( WHAT, __VA_ARGS__) )
#define fe_i_13(WHAT, X, ...)WHAT(X, 13)msvc_expand_va_args( fe_i_12( WHAT, __VA_ARGS__) )
#define fe_i_14(WHAT, X, ...)WHAT(X, 14)msvc_expand_va_args( fe_i_13( WHAT, __VA_ARGS__) )
#define fe_i_15(WHAT, X, ...)WHAT(X, 15)msvc_expand_va_args( fe_i_14( WHAT, __VA_ARGS__) )
#define fe_i_16(WHAT, X, ...)WHAT(X, 16)msvc_expand_va_args( fe_i_15( WHAT, __VA_ARGS__) )
#define fe_i_17(WHAT, X, ...)WHAT(X, 17)msvc_expand_va_args( fe_i_16( WHAT, __VA_ARGS__) )
#define fe_i_18(WHAT, X, ...)WHAT(X, 18)msvc_expand_va_args( fe_i_17( WHAT, __VA_ARGS__) )
#define fe_i_19(WHAT, X, ...)WHAT(X, 19)msvc_expand_va_args( fe_i_18( WHAT, __VA_ARGS__) )
#define fe_i_20(WHAT, X, ...)WHAT(X, 20)msvc_expand_va_args( fe_i_19( WHAT, __VA_ARGS__) )
#define fe_i_21(WHAT, X, ...)WHAT(X, 21)msvc_expand_va_args( fe_i_20( WHAT, __VA_ARGS__) )
#define fe_i_22(WHAT, X, ...)WHAT(X, 22)msvc_expand_va_args( fe_i_21( WHAT, __VA_ARGS__) )
#define fe_i_23(WHAT, X, ...)WHAT(X, 23)msvc_expand_va_args( fe_i_22( WHAT, __VA_ARGS__) )
#define fe_i_24(WHAT, X, ...)WHAT(X, 24)msvc_expand_va_args( fe_i_23( WHAT, __VA_ARGS__) )
#define fe_i_25(WHAT, X, ...)WHAT(X, 25)msvc_expand_va_args( fe_i_24( WHAT, __VA_ARGS__) )
#define fe_i_26(WHAT, X, ...)WHAT(X, 26)msvc_expand_va_args( fe_i_25( WHAT, __VA_ARGS__) )
#define fe_i_27(WHAT, X, ...)WHAT(X, 27)msvc_expand_va_args( fe_i_26( WHAT, __VA_ARGS__) )
#define fe_i_28(WHAT, X, ...)WHAT(X, 28)msvc_expand_va_args( fe_i_27( WHAT, __VA_ARGS__) )
#define fe_i_29(WHAT, X, ...)WHAT(X, 29)msvc_expand_va_args( fe_i_28( WHAT, __VA_ARGS__) )
#define fe_i_30(WHAT, X, ...)WHAT(X, 30)msvc_expand_va_args( fe_i_29( WHAT, __VA_ARGS__) )
#define fe_i_31(WHAT, X, ...)WHAT(X, 31)msvc_expand_va_args( fe_i_30( WHAT, __VA_ARGS__) )
#define fe_i_32(WHAT, X, ...)WHAT(X, 32)msvc_expand_va_args( fe_i_31( WHAT, __VA_ARGS__) )
#define fe_i_33(WHAT, X, ...)WHAT(X, 33)msvc_expand_va_args( fe_i_32( WHAT, __VA_ARGS__) )
#define fe_i_34(WHAT, X, ...)WHAT(X, 34)msvc_expand_va_args( fe_i_33( WHAT, __VA_ARGS__) )
#define fe_i_35(WHAT, X, ...)WHAT(X, 35)msvc_expand_va_args( fe_i_34( WHAT, __VA_ARGS__) )
#define fe_i_36(WHAT, X, ...)WHAT(X, 36)msvc_expand_va_args( fe_i_35( WHAT, __VA_ARGS__) )
#define fe_i_37(WHAT, X, ...)WHAT(X, 37)msvc_expand_va_args( fe_i_36( WHAT, __VA_ARGS__) )
#define fe_i_38(WHAT, X, ...)WHAT(X, 38)msvc_expand_va_args( fe_i_37( WHAT, __VA_ARGS__) )
#define fe_i_39(WHAT, X, ...)WHAT(X, 39)msvc_expand_va_args( fe_i_38( WHAT, __VA_ARGS__) )
#define fe_i_40(WHAT, X, ...)WHAT(X, 40)msvc_expand_va_args( fe_i_39( WHAT, __VA_ARGS__) )
#define fe_i_41(WHAT, X, ...)WHAT(X, 41)msvc_expand_va_args( fe_i_40( WHAT, __VA_ARGS__) )
#define fe_i_42(WHAT, X, ...)WHAT(X, 42)msvc_expand_va_args( fe_i_41( WHAT, __VA_ARGS__) )
#define fe_i_43(WHAT, X, ...)WHAT(X, 43)msvc_expand_va_args( fe_i_42( WHAT, __VA_ARGS__) )
#define fe_i_44(WHAT, X, ...)WHAT(X, 44)msvc_expand_va_args( fe_i_43( WHAT, __VA_ARGS__) )
#define fe_i_45(WHAT, X, ...)WHAT(X, 45)msvc_expand_va_args( fe_i_44( WHAT, __VA_ARGS__) )
#define fe_i_46(WHAT, X, ...)WHAT(X, 46)msvc_expand_va_args( fe_i_45( WHAT, __VA_ARGS__) )
#define fe_i_47(WHAT, X, ...)WHAT(X, 47)msvc_expand_va_args( fe_i_46( WHAT, __VA_ARGS__) )
#define fe_i_48(WHAT, X, ...)WHAT(X, 48)msvc_expand_va_args( fe_i_47( WHAT, __VA_ARGS__) )
#define fe_i_49(WHAT, X, ...)WHAT(X, 49)msvc_expand_va_args( fe_i_48( WHAT, __VA_ARGS__) )
#define fe_i_50(WHAT, X, ...)WHAT(X, 50)msvc_expand_va_args( fe_i_49( WHAT, __VA_ARGS__) )
#define fe_i_51(WHAT, X, ...)WHAT(X, 51)msvc_expand_va_args( fe_i_50( WHAT, __VA_ARGS__) )
#define fe_i_52(WHAT, X, ...)WHAT(X, 52)msvc_expand_va_args( fe_i_51( WHAT, __VA_ARGS__) )
#define fe_i_53(WHAT, X, ...)WHAT(X, 53)msvc_expand_va_args( fe_i_52( WHAT, __VA_ARGS__) )
#define fe_i_54(WHAT, X, ...)WHAT(X, 54)msvc_expand_va_args( fe_i_53( WHAT, __VA_ARGS__) )
#define fe_i_55(WHAT, X, ...)WHAT(X, 55)msvc_expand_va_args( fe_i_54( WHAT, __VA_ARGS__) )
#define fe_i_56(WHAT, X, ...)WHAT(X, 56)msvc_expand_va_args( fe_i_55( WHAT, __VA_ARGS__) )
#define fe_i_57(WHAT, X, ...)WHAT(X, 57)msvc_expand_va_args( fe_i_56( WHAT, __VA_ARGS__) )
#define fe_i_58(WHAT, X, ...)WHAT(X, 58)msvc_expand_va_args( fe_i_57( WHAT, __VA_ARGS__) )
#define fe_i_59(WHAT, X, ...)WHAT(X, 59)msvc_expand_va_args( fe_i_58( WHAT, __VA_ARGS__) )
#define fe_i_60(WHAT, X, ...)WHAT(X, 60)msvc_expand_va_args( fe_i_59( WHAT, __VA_ARGS__) )
#define fe_i_61(WHAT, X, ...)WHAT(X, 61)msvc_expand_va_args( fe_i_60( WHAT, __VA_ARGS__) )
#define fe_i_62(WHAT, X, ...)WHAT(X, 62)msvc_expand_va_args( fe_i_61( WHAT, __VA_ARGS__) )
#define fe_i_63(WHAT, X, ...)WHAT(X, 63)msvc_expand_va_args( fe_i_62( WHAT, __VA_ARGS__) )
#define fe_i_64(WHAT, X, ...)WHAT(X, 64)msvc_expand_va_args( fe_i_63( WHAT, __VA_ARGS__) )
#define fe_i_65(WHAT, X, ...)WHAT(X, 65)msvc_expand_va_args( fe_i_64( WHAT, __VA_ARGS__) )
#define fe_i_66(WHAT, X, ...)WHAT(X, 66)msvc_expand_va_args( fe_i_65( WHAT, __VA_ARGS__) )
#define fe_i_67(WHAT, X, ...)WHAT(X, 67)msvc_expand_va_args( fe_i_66( WHAT, __VA_ARGS__) )
#define fe_i_68(WHAT, X, ...)WHAT(X, 68)msvc_expand_va_args( fe_i_67( WHAT, __VA_ARGS__) )
#define fe_i_69(WHAT, X, ...)WHAT(X, 69)msvc_expand_va_args( fe_i_68( WHAT, __VA_ARGS__) )
#define fe_i_70(WHAT, X, ...)WHAT(X, 70)msvc_expand_va_args( fe_i_69( WHAT, __VA_ARGS__) )
#define fe_i_71(WHAT, X, ...)WHAT(X, 71)msvc_expand_va_args( fe_i_70( WHAT, __VA_ARGS__) )
#define fe_i_72(WHAT, X, ...)WHAT(X, 72)msvc_expand_va_args( fe_i_71( WHAT, __VA_ARGS__) )
#define fe_i_73(WHAT, X, ...)WHAT(X, 73)msvc_expand_va_args( fe_i_72( WHAT, __VA_ARGS__) )
#define fe_i_74(WHAT, X, ...)WHAT(X, 74)msvc_expand_va_args( fe_i_73( WHAT, __VA_ARGS__) )
#define fe_i_75(WHAT, X, ...)WHAT(X, 75)msvc_expand_va_args( fe_i_74( WHAT, __VA_ARGS__) )
#define fe_i_76(WHAT, X, ...)WHAT(X, 76)msvc_expand_va_args( fe_i_75( WHAT, __VA_ARGS__) )
#define fe_i_77(WHAT, X, ...)WHAT(X, 77)msvc_expand_va_args( fe_i_76( WHAT, __VA_ARGS__) )
#define fe_i_78(WHAT, X, ...)WHAT(X, 78)msvc_expand_va_args( fe_i_77( WHAT, __VA_ARGS__) )
#define fe_i_79(WHAT, X, ...)WHAT(X, 79)msvc_expand_va_args( fe_i_78( WHAT, __VA_ARGS__) )
#define fe_i_80(WHAT, X, ...)WHAT(X, 80)msvc_expand_va_args( fe_i_79( WHAT, __VA_ARGS__) )
#define fe_i_81(WHAT, X, ...)WHAT(X, 81)msvc_expand_va_args( fe_i_80( WHAT, __VA_ARGS__) )
#define fe_i_82(WHAT, X, ...)WHAT(X, 82)msvc_expand_va_args( fe_i_81( WHAT, __VA_ARGS__) )
#define fe_i_83(WHAT, X, ...)WHAT(X, 83)msvc_expand_va_args( fe_i_82( WHAT, __VA_ARGS__) )
#define fe_i_84(WHAT, X, ...)WHAT(X, 84)msvc_expand_va_args( fe_i_83( WHAT, __VA_ARGS__) )
#define fe_i_85(WHAT, X, ...)WHAT(X, 85)msvc_expand_va_args( fe_i_84( WHAT, __VA_ARGS__) )
#define fe_i_86(WHAT, X, ...)WHAT(X, 86)msvc_expand_va_args( fe_i_85( WHAT, __VA_ARGS__) )
#define fe_i_87(WHAT, X, ...)WHAT(X, 87)msvc_expand_va_args( fe_i_86( WHAT, __VA_ARGS__) )
#define fe_i_88(WHAT, X, ...)WHAT(X, 88)msvc_expand_va_args( fe_i_87( WHAT, __VA_ARGS__) )
#define fe_i_89(WHAT, X, ...)WHAT(X, 89)msvc_expand_va_args( fe_i_88( WHAT, __VA_ARGS__) )
#define fe_i_90(WHAT, X, ...)WHAT(X, 90)msvc_expand_va_args( fe_i_89( WHAT, __VA_ARGS__) )
#define fe_i_91(WHAT, X, ...)WHAT(X, 91)msvc_expand_va_args( fe_i_90( WHAT, __VA_ARGS__) )
#define fe_i_92(WHAT, X, ...)WHAT(X, 92)msvc_expand_va_args( fe_i_91( WHAT, __VA_ARGS__) )
#define fe_i_93(WHAT, X, ...)WHAT(X, 93)msvc_expand_va_args( fe_i_92( WHAT, __VA_ARGS__) )
#define fe_i_94(WHAT, X, ...)WHAT(X, 94)msvc_expand_va_args( fe_i_93( WHAT, __VA_ARGS__) )
#define fe_i_95(WHAT, X, ...)WHAT(X, 95)msvc_expand_va_args( fe_i_94( WHAT, __VA_ARGS__) )
#define fe_i_96(WHAT, X, ...)WHAT(X, 96)msvc_expand_va_args( fe_i_95( WHAT, __VA_ARGS__) )
#define fe_i_97(WHAT, X, ...)WHAT(X, 97)msvc_expand_va_args( fe_i_96( WHAT, __VA_ARGS__) )
#define fe_i_98(WHAT, X, ...)WHAT(X, 98)msvc_expand_va_args( fe_i_97( WHAT, __VA_ARGS__) )
#define fe_i_99(WHAT, X, ...)WHAT(X, 99)msvc_expand_va_args( fe_i_98( WHAT, __VA_ARGS__) )
#define fe_i_100(WHAT, X, ...)WHAT(X, 100)msvc_expand_va_args( fe_i_99( WHAT, __VA_ARGS__) )
#define fe_i_101(WHAT, X, ...)WHAT(X, 101)msvc_expand_va_args( fe_i_100( WHAT, __VA_ARGS__) )
#define fe_i_102(WHAT, X, ...)WHAT(X, 102)msvc_expand_va_args( fe_i_101( WHAT, __VA_ARGS__) )
#define fe_i_103(WHAT, X, ...)WHAT(X, 103)msvc_expand_va_args( fe_i_102( WHAT, __VA_ARGS__) )
#define fe_i_104(WHAT, X, ...)WHAT(X, 104)msvc_expand_va_args( fe_i_103( WHAT, __VA_ARGS__) )
#define fe_i_105(WHAT, X, ...)WHAT(X, 105)msvc_expand_va_args( fe_i_104( WHAT, __VA_ARGS__) )
#define fe_i_106(WHAT, X, ...)WHAT(X, 106)msvc_expand_va_args( fe_i_105( WHAT, __VA_ARGS__) )
#define fe_i_107(WHAT, X, ...)WHAT(X, 107)msvc_expand_va_args( fe_i_106( WHAT, __VA_ARGS__) )
#define fe_i_108(WHAT, X, ...)WHAT(X, 108)msvc_expand_va_args( fe_i_107( WHAT, __VA_ARGS__) )
#define fe_i_109(WHAT, X, ...)WHAT(X, 109)msvc_expand_va_args( fe_i_108( WHAT, __VA_ARGS__) )
#define fe_i_110(WHAT, X, ...)WHAT(X, 110)msvc_expand_va_args( fe_i_109( WHAT, __VA_ARGS__) )
#define fe_i_111(WHAT, X, ...)WHAT(X, 111)msvc_expand_va_args( fe_i_110( WHAT, __VA_ARGS__) )
#define fe_i_112(WHAT, X, ...)WHAT(X, 112)msvc_expand_va_args( fe_i_111( WHAT, __VA_ARGS__) )
#define fe_i_113(WHAT, X, ...)WHAT(X, 113)msvc_expand_va_args( fe_i_112( WHAT, __VA_ARGS__) )
#define fe_i_114(WHAT, X, ...)WHAT(X, 114)msvc_expand_va_args( fe_i_113( WHAT, __VA_ARGS__) )
#define fe_i_115(WHAT, X, ...)WHAT(X, 115)msvc_expand_va_args( fe_i_114( WHAT, __VA_ARGS__) )
#define fe_i_116(WHAT, X, ...)WHAT(X, 116)msvc_expand_va_args( fe_i_115( WHAT, __VA_ARGS__) )
#define fe_i_117(WHAT, X, ...)WHAT(X, 117)msvc_expand_va_args( fe_i_116( WHAT, __VA_ARGS__) )
#define fe_i_118(WHAT, X, ...)WHAT(X, 118)msvc_expand_va_args( fe_i_117( WHAT, __VA_ARGS__) )
#define fe_i_119(WHAT, X, ...)WHAT(X, 119)msvc_expand_va_args( fe_i_118( WHAT, __VA_ARGS__) )
#define fe_i_120(WHAT, X, ...)WHAT(X, 120)msvc_expand_va_args( fe_i_119( WHAT, __VA_ARGS__) )
#define fe_i_121(WHAT, X, ...)WHAT(X, 121)msvc_expand_va_args( fe_i_120( WHAT, __VA_ARGS__) )
#define fe_i_122(WHAT, X, ...)WHAT(X, 122)msvc_expand_va_args( fe_i_121( WHAT, __VA_ARGS__) )
#define fe_i_123(WHAT, X, ...)WHAT(X, 123)msvc_expand_va_args( fe_i_122( WHAT, __VA_ARGS__) )
#define fe_i_124(WHAT, X, ...)WHAT(X, 124)msvc_expand_va_args( fe_i_123( WHAT, __VA_ARGS__) )
#define fe_i_125(WHAT, X, ...)WHAT(X, 125)msvc_expand_va_args( fe_i_124( WHAT, __VA_ARGS__) )
#define fe_i_126(WHAT, X, ...)WHAT(X, 126)msvc_expand_va_args( fe_i_125( WHAT, __VA_ARGS__) )


//... repeat as needed

#define mc_get_macro(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,_101,_102,_103,_104,_105,_106,_107,_108,_109,_110,_111,_112,_113,_114,_115,_116,_117,_118,_119,_120,_121,_122,_123,_124,_125,NAME, ...) NAME

#define mc_args_count(...) msvc_expand_va_args( mc_get_macro( __VA_ARGS__, 125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1) )

#define mc_for_each(action,...) \
  msvc_expand_va_args( mc_get_macro(__VA_ARGS__, fe_125,fe_124,fe_123,fe_122,fe_121,fe_120,fe_119,fe_118,fe_117,fe_116,fe_115,fe_114,fe_113,fe_112,fe_111,fe_110,fe_109,fe_108,fe_107,fe_106,fe_105,fe_104,fe_103,fe_102,fe_101,fe_100,fe_99,fe_98,fe_97,fe_96,fe_95,fe_94,fe_93,fe_92,fe_91,fe_90,fe_89,fe_88,fe_87,fe_86,fe_85,fe_84,fe_83,fe_82,fe_81,fe_80,fe_79,fe_78,fe_77,fe_76,fe_75,fe_74,fe_73,fe_72,fe_71,fe_70,fe_69,fe_68,fe_67,fe_66,fe_65,fe_64,fe_63,fe_62,fe_61,fe_60,fe_59,fe_58,fe_57,fe_56,fe_55,fe_54,fe_53,fe_52,fe_51,fe_50,fe_49,fe_48,fe_47,fe_46,fe_45,fe_44,fe_43,fe_42,fe_41,fe_40,fe_39,fe_38,fe_37,fe_36,fe_35,fe_34,fe_33,fe_32,fe_31,fe_30,fe_29,fe_28,fe_27,fe_26,fe_25,fe_24,fe_23,fe_22,fe_21,fe_20,fe_19,fe_18,fe_17,fe_16,fe_15,fe_14,fe_13,fe_12,fe_11,fe_10,fe_9,fe_8,fe_7,fe_6,fe_5,fe_4,fe_3,fe_2,fe_1)(action, __VA_ARGS__) )

#define mc_for_each_with_index(action, ...) \
  msvc_expand_va_args( mc_get_macro(__VA_ARGS__, fe_i_125,fe_i_124,fe_i_123,fe_i_122,fe_i_121,fe_i_120,fe_i_119,fe_i_118,fe_i_117,fe_i_116,fe_i_115,fe_i_114,fe_i_113,fe_i_112,fe_i_111,fe_i_110,fe_i_109,fe_i_108,fe_i_107,fe_i_106,fe_i_105,fe_i_104,fe_i_103,fe_i_102,fe_i_101,fe_i_100,fe_i_99,fe_i_98,fe_i_97,fe_i_96,fe_i_95,fe_i_94,fe_i_93,fe_i_92,fe_i_91,fe_i_90,fe_i_89,fe_i_88,fe_i_87,fe_i_86,fe_i_85,fe_i_84,fe_i_83,fe_i_82,fe_i_81,fe_i_80,fe_i_79,fe_i_78,fe_i_77,fe_i_76,fe_i_75,fe_i_74,fe_i_73,fe_i_72,fe_i_71,fe_i_70,fe_i_69,fe_i_68,fe_i_67,fe_i_66,fe_i_65,fe_i_64,fe_i_63,fe_i_62,fe_i_61,fe_i_60,fe_i_59,fe_i_58,fe_i_57,fe_i_56,fe_i_55,fe_i_54,fe_i_53,fe_i_52,fe_i_51,fe_i_50,fe_i_49,fe_i_48,fe_i_47,fe_i_46,fe_i_45,fe_i_44,fe_i_43,fe_i_42,fe_i_41,fe_i_40,fe_i_39,fe_i_38,fe_i_37,fe_i_36,fe_i_35,fe_i_34,fe_i_33,fe_i_32,fe_i_31,fe_i_30,fe_i_29,fe_i_28,fe_i_27,fe_i_26,fe_i_25,fe_i_24,fe_i_23,fe_i_22,fe_i_21,fe_i_20,fe_i_19,fe_i_18,fe_i_17,fe_i_16,fe_i_15,fe_i_14,fe_i_13,fe_i_12,fe_i_11,fe_i_10,fe_i_9,fe_i_8,fe_i_7,fe_i_6,fe_i_5,fe_i_4,fe_i_3,fe_i_2,fe_i_1)(action, __VA_ARGS__) )
 
#define mc_remove_first_arg_(first, ...) __VA_ARGS__
#define mc_remove_first_arg(...) msvc_expand_va_args( mc_remove_first_arg_(__VA_ARGS__) )

#endif // MACROS_H
